include:
  - board: xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: totem_left_with_studio
  - board: xiao_ble
    shield: totem_right
# there is no settingsreset (needed) for the XIAO
